frase = ' Curso em Vídeo Python' 
dividida = frase.split()   

print(frase[::])
print(frase.count('o'))
print(frase.upper())
print(frase.lower())
print(len(frase))
print(frase.strip())
print(frase.replace('Python', 'Android'))
print(frase.title())
print(frase.capitalize())
print('Curso' in frase)
print('Bernardo' in frase)
print(frase.find('Vídeo'))
print(frase.find('Bernardo'))
print(frase.lower().find('vídeo'))
print(frase.split())
print(dividida)
print(dividida[0:3])
print(dividida[2] [3])