x = input('Digite algo: ')

print('É numérico?', x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanumérico?', x.isalnum())
print('Está em maiúsculas?', x.isupper())
print('Está em minúsculas?', x.islower())
print('Está capitalizado?', x.istitle())
print('É imprimível?', x.isprintable())
print('É um espaço?', x.isspace())
print('É um identificador válido?', x.isidentifier())
print('É decimal?', x.isdecimal())
print('É um dígito?', x.isdigit())
print('Tipo:', type(x))